# -*- coding: utf-8 -*-
"""classification_test_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14NA2yHf2atSEGtP50P-MOWZP_8kCqRnl
"""

import torch
import torch.nn as nn
from torchvision import models, transforms
import cv2
import matplotlib.pyplot as plt

# -----------------------------
# 1️⃣ Define Class Names
# -----------------------------
class_names = [
    "Aortic enlargement",
    "Atelectasis",
    "Calcification",
    "Cardiomegaly",
    "Consolidation",
    "ILD",
    "Infiltration",
    "Lung Opacity",
    "Nodule/Mass",
    "Other lesion",
    "Pleural effusion",
    "Pleural thickening",
    "Pneumothorax",
    "Pulmonary fibrosis"
]

num_classes = len(class_names)

# -----------------------------
# 2️⃣ Load DenseNet121 Model
# -----------------------------
model = models.densenet121(pretrained=False)
model.classifier = nn.Linear(model.classifier.in_features, num_classes)

# Load trained weights
model.load_state_dict(torch.load("/content/densenet121_chest_model.pth", map_location=torch.device('cpu')))
model.eval()

print("Model Loaded Successfully ✅")

# -----------------------------
# 3️⃣ Image Preprocessing
# -----------------------------
transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

# -----------------------------
# 4️⃣ Load and Prepare Image
# -----------------------------
image_path = "/content/2a180035c17769657f1d89651ff4babd.png"

img = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

input_tensor = transform(img_rgb)
input_tensor = input_tensor.unsqueeze(0)  # Add batch dimension

# -----------------------------
# 5️⃣ Prediction
# -----------------------------
with torch.no_grad():
    outputs = model(input_tensor)
    probabilities = torch.sigmoid(outputs)

# -----------------------------
# 6️⃣ Print Detected Diseases
# -----------------------------
threshold = 0.5

print("\nDetected Diseases:")
found = False

for i, prob in enumerate(probabilities[0]):
    if prob > threshold:
        print(f"{class_names[i]}: {prob.item()*100:.2f}%")
        found = True

if not found:
    print("No disease detected (Normal)")

# -----------------------------
# 7️⃣ Show Image
# -----------------------------
plt.imshow(img_rgb)
plt.title("Chest X-ray Prediction")
plt.axis("off")
plt.show()