# -*- coding: utf-8 -*-
"""Classification_train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z0muM8cuNzs0mnONa_ZUlweXPXPlqUt-
"""

import torch
torch.cuda.is_available()

from google.colab import drive
drive.mount('/content/drive')

base_path = "/content/drive/MyDrive/processing_image/processed_5000"

train_image_dir = base_path + "/train/images"
train_label_dir = base_path + "/train/labels"

val_image_dir = base_path + "/val/images"
val_label_dir = base_path + "/val/labels"



import os

max_class = 0

for file in os.listdir(train_label_dir):

    if not file.endswith(".txt"):
        continue

    with open(os.path.join(train_label_dir, file), "r") as f:
        for line in f:
            class_id = int(line.split()[0])
            if class_id > max_class:
                max_class = class_id

num_classes = max_class + 1

print("Total classes:", num_classes)

import torch
from torch.utils.data import Dataset
import cv2
import os
import numpy as np

class YOLOMultiLabelDataset(Dataset):
    def __init__(self, image_dir, label_dir, transform=None, num_classes=14):
        self.image_dir = image_dir
        self.label_dir = label_dir
        self.transform = transform
        self.images = [f for f in os.listdir(image_dir) if f.endswith((".png",".jpg",".jpeg"))]
        self.num_classes = num_classes

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]
        img_path = os.path.join(self.image_dir, img_name)

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        if self.transform:
            image = self.transform(image)

        labels = np.zeros(self.num_classes)

        label_path = os.path.join(
            self.label_dir,
            img_name.replace(".png",".txt").replace(".jpg",".txt")
        )

        if os.path.exists(label_path):
            with open(label_path, "r") as f:
                for line in f:
                    class_id = int(line.split()[0])
                    if class_id < self.num_classes:
                        labels[class_id] = 1

        return image, torch.tensor(labels, dtype=torch.float32)

from torchvision import transforms

transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224,224)),
    transforms.ToTensor(),
])

from torch.utils.data import DataLoader

train_dataset = YOLOMultiLabelDataset(
    train_image_dir,
    train_label_dir,
    transform,
    num_classes=14
)

val_dataset = YOLOMultiLabelDataset(
    val_image_dir,
    val_label_dir,
    transform,
    num_classes=14
)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)

import torchvision.models as models
import torch.nn as nn

model = models.densenet121(pretrained=True)
model.classifier = nn.Linear(model.classifier.in_features, 14)

device = torch.device("cuda")
model = model.to(device)

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

epochs = 10

for epoch in range(epochs):
    model.train()
    total_loss = 0

    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss/len(train_loader)}")

import torch

model.eval()

correct = 0
total = 0

with torch.no_grad():
    for images, labels in val_loader:
        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)

        # Apply sigmoid
        preds = torch.sigmoid(outputs)

        # Convert to 0 or 1 (threshold = 0.5)
        preds = (preds > 0.5).float()

        # Count correct predictions
        correct += (preds == labels).sum().item()
        total += labels.numel()

accuracy = correct / total
print("Validation Accuracy:", accuracy)

best_acc = 0

for epoch in range(epochs):
    # training code

    # after validation
    if accuracy > best_acc:
        best_acc = accuracy
        torch.save(model.state_dict(),
                   "/content/drive/MyDrive/best_chest_model.pth")
        print("Best model saved!")

import os

print(image_path)
print(os.path.exists(image_path))

import os

test_image_dir = "/content/drive/MyDrive/processing_image/processed_5000/test/images"

print(os.listdir(test_image_dir)[:10])

import os

test_image_dir = "/content/drive/MyDrive/processing_image/processed_5000/test/images"

image_name = os.listdir(test_image_dir)[0]
image_path = os.path.join(test_image_dir, image_name)

print("Using image:", image_name)
print("Exists:", os.path.exists(image_path))

import cv2

image = cv2.imread(image_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

image = transform(image)
image = image.unsqueeze(0).to(device)

model.eval()

with torch.no_grad():
    outputs = model(image)
    probs = torch.sigmoid(outputs)
    preds = (probs > 0.5).float()

print("Probabilities:", probs.cpu().numpy())
print("Predicted Labels:", preds.cpu().numpy())

criterion = torch.nn.BCEWithLogitsLoss()

import torchvision.models as models
import torch.nn as nn

model = models.densenet121(pretrained=True)
model.classifier = nn.Linear(model.classifier.in_features, 14)

from torchvision import transforms

transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

epochs = 20

preds = (probs > 0.2).float()

print("Average probability:", probs.mean().item())

model = models.densenet121(pretrained=True)

# Get input features automatically
in_features = model.classifier.in_features

# Change final layer to 14 classes
model.classifier = nn.Linear(in_features, 14)

model = model.to(device)

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.models as models
from torchvision import transforms

criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

epochs = 15

for epoch in range(epochs):
    model.train()
    total_loss = 0

    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss/len(train_loader)}")

model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in val_loader:
        images = images.to(device)
        labels = labels.to(device)

        outputs = model(images)
        probs = torch.sigmoid(outputs)
        preds = (probs > 0.2).float()

        correct += (preds == labels).sum().item()
        total += labels.numel()

print("Validation Accuracy:", correct / total)

model.eval()

from torchvision import transforms

transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

import cv2

image_path = "/content/drive/MyDrive/processing_image/processed_5000/test/images/98a4e71a168d133927c15bf51c134f65.png"

image = cv2.imread(image_path)

if image is None:
    print("Image not found ❌")
else:
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    print("Image loaded ✅")

image = transform(image)
image = image.unsqueeze(0).to(device)   # Add batch dimension

import torch

with torch.no_grad():
    outputs = model(image)
    probs = torch.sigmoid(outputs)

print("Probabilities:", probs.cpu().numpy())
print("Average Probability:", probs.mean().item())

torch.save(model.state_dict(), "/content/drive/MyDrive/densenet121_chest_model.pth")